name: Lint

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint
        uses: ChenCMD/datapack-linter@v1
        with:
          notOutputSuccess: true
          checkAlwaysAllFile: true
          ignoreLintPathPattern: |
            ny2023:fireworks/**
